// Generated by Selenium IDE
package ies.lab4;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
// import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.hamcrest.MatcherAssert.assertThat;

import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

// import org.openqa.selenium.htmlunit.HtmlUnitDriver;

import io.github.bonigarcia.seljup.SeleniumJupiter;

@ExtendWith(SeleniumJupiter.class)
public class SeleniumObjectPatternHeadlessTest {

  @Test
  public void test(HtmlUnitDriver driver) {


    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(550, 691));

    HomePage homePage = new HomePage(driver);

    homePage.chooseOrigin("Philadelphia");
    homePage.chooseDestination("New York");
    homePage.clickOnFindFlightsButton();

    ReservePage reservePage = new ReservePage(driver);
    assertTrue(reservePage.isOpened());

    reservePage.clickOnFlight(0);

    PurchasePage purchasePage = new PurchasePage(driver);
    assertTrue(purchasePage.isOpened());

    purchasePage.setName("Sussy boy");
    purchasePage.setAddress("123 main st.");
    purchasePage.setCity("That one");
    purchasePage.setState("Goias");
    purchasePage.setZipCode("54321");
    purchasePage.setCreditCardNumber("111232");
    purchasePage.setCardType(1);
    purchasePage.setCreditCardMonth("12");
    purchasePage.setCreditCardYear("2017");
    purchasePage.setNameOnCard("Sussy Boy");
    purchasePage.rememberMeCheck();
    purchasePage.purchaseButtonClick();
 
    ConfirmationPage confirmationPage = new ConfirmationPage(driver);
    assertTrue(confirmationPage.isOpened());

  }
}
