package ies.hw.hw1;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class FrontendSteps {
    
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    
    @Given("the website just opened")
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(640, 752));
    }

    @When("I choose for the {string} API")
    public void chooseApi(String api) {
        System.out.println("You choosed api: " + api);
    }

    @And("I choose the country {string}")
    public void chooseCountry(String country) {
        System.out.println("Country: " + country);
    }

    @And("I choose the date range between 12 and 18 of April")
    public void setDates() {
        System.out.println("sys");
    }

    @Then("new deaths on day {int} is {int}")
    public void assertDeaths(int day, int newDeaths) {
        System.out.println("Sussy Day: " + day);
        System.out.println("NewDeaths: " + newDeaths);
    }
}
