package ies.hw.hw1;

// Generated by Selenium IDE

import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.Assert.assertTrue;


public class FrontendSteps {
    
    private WebDriver driver;
    private Map<String, Object> vars;

    JavascriptExecutor js;
    @Given("the website just opened")
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(640, 752));
    }

    @When("I choose for the {string} API")
    public void chooseApi(String api) {
        if (api.equals("Api 1")) {
            assertTrue(driver.findElement(By.name("row-radio-buttons-group")).isSelected());
        }
        System.out.println("You choosed api: " + api);

    }

    @And("I choose the country {string}")
    public void chooseCountry(String country) {
        System.out.println("Country: " + country);
        driver.findElement(By.id(":r3:")).click();
        driver.findElement(By.id(":r3:")).sendKeys(country);
        driver.findElement(By.id(":r3:")).sendKeys(Keys.DOWN);
        driver.findElement(By.id(":r3:")).sendKeys(Keys.ENTER);
    }

    @And("I choose the date range between 12 and 18 of April")
    public void setDates() {

        driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(3) .MuiSvgIcon-root")).click();
        driver.findElement(By.cssSelector(".css-mvmu1r:nth-child(3) > div:nth-child(3) > .MuiButtonBase-root")).click();
        driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(4) .MuiSvgIcon-root")).click();
        driver.findElement(By.cssSelector(".css-mvmu1r:nth-child(4) > div:nth-child(2) > .MuiButtonBase-root")).click();
    }

    @Then("new deaths on day {int} is {int}")
    public void assertDeaths(int day, int newDeaths) {
        int multiplier = day - 11;
        System.out.println("Sussy Day: " + day);
        System.out.println("NewDeaths: " + newDeaths);
        assertThat(driver.findElement(By.cssSelector("h2:nth-child(" + (9 * multiplier - 1) + ")"))
                .getText(), is("Covid Data for 2022-04-"+day));
        driver.quit();
    }
}
